name: jikart
description: A simple Dart interface to jikan.moe
version: 0.3.0
homepage: https://github.com/ale183/Jikart
issue_tracker: https://github.com/ale183/Jikart/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
